import streamlit as st
import google.generativeai as genai
import requests
import io
from PIL import Image
from fpdf import FPDF

# --- KONFIGURASI HALAMAN ---
st.set_page_config(page_title="Mesin Fotonis Pro v2", page_icon="🏗️", layout="wide")

# --- SIGNATURE ---
SIGNATURE = "Developed by **Adjie Agung**"

# --- AMBIL API KEYS ---
try:
    GEMINI_KEY = st.secrets["GEMINI_API_KEY"]
    REMOVE_BG_API_KEY = st.secrets["REMOVE_BG_API_KEY"]
    genai.configure(api_key=GEMINI_KEY)
except KeyError:
    st.error("⚠️ API Key belum lengkap di Streamlit Secrets.")
    st.stop()

st.title("🏗️ Mesin Fotonis Pro: Enterprise Edition")
st.markdown(f"**Sistem Otomasi Katalog Tatsuo & AIMIX** | {SIGNATURE}")

def remove_bg_api(image_bytes):
    response = requests.post(
        'https://api.remove.bg/v1.0/removebg',
        files={'image_file': image_bytes},
        data={'size': 'auto'},
        headers={'X-Api-Key': REMOVE_BG_API_KEY},
    )
    return response.content if response.status_code == requests.codes.ok else None

def analisa_gemini_pro(image_bytes):
    model = genai.GenerativeModel('gemini-flash-latest')
    img_pil = Image.open(io.BytesIO(image_bytes))
    
    prompt = """
    Anda adalah pakar pemasaran alat berat global. Analisa gambar produk ini:
    1. Nama Produk Komersial.
    2. Spesifikasi Teknis (Estimasi kapasitas, komponen, material).
    3. Copywriting AIDA (Attention, Interest, Desire, Action) dalam DUA Bahasa: Indonesia dan Inggris.
    Berikan hasil dalam format Markdown yang elegan.
    """
    response = model.generate_content([prompt, img_pil])
    return response.text

def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    # Membersihkan karakter non-latin untuk PDF sederhana
    clean_text = text.replace('*', '').replace('#', '')
    pdf.multi_cell(0, 10, txt=clean_text)
    pdf.ln(10)
    pdf.set_font("Arial", 'I', size=8)
    pdf.cell(0, 10, txt="Generated by Mesin Fotonis Pro - Dev by Adjie Agung", ln=True, align='C')
    return pdf.output(dest='S').encode('latin-1')

# --- UI ---
uploaded_file = st.file_uploader("Upload Foto Alat Berat", type=['jpg', 'png', 'jpeg'])

if uploaded_file:
    file_bytes = uploaded_file.read()
    col1, col2 = st.columns(2)
    
    with col1:
        st.image(file_bytes, caption="Original Asset", use_column_width="always")
    
    with col2:
        if st.button("✨ Bersihkan Gambar"):
            with st.spinner("Menghapus background..."):
                result_bytes = remove_bg_api(file_bytes)
                if result_bytes:
                    st.session_state['gambar_bersih'] = result_bytes 
                    st.image(result_bytes, caption="Clean Asset", use_column_width="always")
                    st.success("Background Cleaned!")

    if 'gambar_bersih' in st.session_state:
        st.divider()
        if st.button("🌍 Jalankan Analisa Global"):
            with st.spinner("Gemini sedang bekerja..."):
                try:
                    hasil_ai = analisa_gemini_pro(st.session_state['gambar_bersih'])
                    st.session_state['last_result'] = hasil_ai
                    st.success("Analisa Selesai!")
                except Exception as e:
                    st.error(f"Error: {e}")

        if 'last_result' in st.session_state:
            with st.container(border=True):
                st.markdown(st.session_state['last_result'])
                st.markdown(f"--- \n <small>{SIGNATURE}</small>", unsafe_allow_html=True)
            
            # Fitur Download
            pdf_data = create_pdf(st.session_state['last_result'])
            st.download_button(
                label="📥 Download Hasil (PDF)",
                data=pdf_data,
                file_name="Analisa_Produk_Tatsuo_Aimix.pdf",
                mime="application/pdf"
            )
